monitoring: Add monitoring architecture doc
Tendrl/documentation pull request #51
Opened 2016-11-01 16:32 UTC by anmolbabu

Add monitoring architecture doc

Issue: https://github.com/Tendrl/documentation/issues/40
Jira: https://tendrl.atlassian.net/browse/TEN-49, https://github.com/Tendrl/documentation/issues/32, https://tendrl.atlassian.net/browse/TEN-84
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

2016-11-01 16:37 UTC, anmolbabu commented
@nthomas-redhat @shtripat @brainfunked @anupnivargi @anupnivargi Please review

2016-11-04 09:13 UTC, brainfunked requested changes
In the diagram, I would suggest colour coding the boxes to depict the stacks the boxes belong to. In this scenario core and performance monitoring stacks would need to be depicted with their specific colours. The other boxes could be left colourless.

2016-11-04 09:15 UTC, shtripat commented on tendrl-monitoring-architecture.adoc
> +** Current time series data needed for automated conditional triggers.
Is it correct?

2016-11-04 09:15 UTC, shtripat commented on tendrl-monitoring-architecture.adoc
> +** Monitoring and gathering of the system’s status, including collection of
node agent does gathering of time series data??

2016-11-04 09:17 UTC, brainfunked commented on tendrl-monitoring-architecture.adoc
> +** Monitoring and gathering of the system’s status, including collection of
This was an older document, which needs to be updated with the appropriate details from the newly finalised monitoring architecture.

2016-11-04 09:26 UTC, shtripat commented on tendrl-monitoring-architecture.adoc
> +** Monitoring and gathering of the system’s status, including collection of
@anmolbabu can you please update this?

2016-11-08 09:45 UTC, anmolbabu commented
@brainfunked @shtripat @nthomas-redhat @anupnivargi I have incorporated comments. Please review.

2016-11-08 15:00 UTC, brainfunked requested changes

2016-11-08 15:00 UTC, brainfunked commented on tendrl-monitoring-architecture.adoc
> +  ** A BSD Licensed python tool by name flask is used for serving the
This doesn't need to be part of the design discussion. Perhaps can be explained in a separate section on the selection of tools.

2016-11-08 15:00 UTC, brainfunked commented on tendrl-monitoring-architecture.adoc
> +        started.
The monitoring application should be treated as an add-on stack. This means that the corresponding code, templates, configurations, flows etc. all need to be shipped for the monitoring stack should be shipped separately, with an assumption that the core stack is already started.

I would suggest that the flow framework from the core stack be reused for deploying the monitoring stack.
1. Install the monitoring application.
2. Monitoring application connects to etcd and uploads the default monitoring configuration and flows.
3. Monitoring application triggers the monitoring provisioning flow on every node for node monitoring via the core API.
4. The provisioning flow for the monitoring stack installs the collectd-related pieces on every node and generates the configuration files from templates shipped with the collectd plugins on nodes.

2016-11-09 12:03 UTC, fbalak commented on api/monitoring-api.adoc
> +GET /moitoring/nodes/<node_name>/monitored_types
There is probably typing error: monitoring instead of moitoring.

2016-12-03 09:44 UTC, anmolbabu commented on api/monitoring-api.adoc
> +GET /moitoring/nodes/<node_name>/monitored_types
Yes, that was a typo :) .. Thanks for pointing..

2016-12-03 09:45 UTC, anmolbabu commented on tendrl-monitoring-architecture.adoc
> +  ** A BSD Licensed python tool by name flask is used for serving the
Done. Removed it from here..

2016-12-03 11:27 UTC, anmolbabu commented on tendrl-monitoring-architecture.adoc
> +        started.
Done

2016-12-03 11:29 UTC, anmolbabu commented
@brainfunked @nthomas-redhat @shtripat @r0h4n @fbalak Comments incorporated. Please review

2018-01-24 21:25 UTC, closed without merging