Provisioning ceph cluster on centos
Tendrl/documentation pull request #56
Opened 2016-11-15 14:55 UTC by GowthamShanmugam

Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>

2016-11-17 15:07 UTC, shtripat reviewed
This use of ceph-installer is stop gap arrangement and ideally upstream we should mention usage of ceph-ansible rather for creation of ceph cluster

2016-11-17 15:07 UTC, shtripat commented on create_ceph_cluster_on_centos.adoc
> +using Rhel machine as sever.
"This document describes the mechanism to create ceph cluster on CentOS nodes"

2016-11-17 15:07 UTC, shtripat commented on create_ceph_cluster_on_centos.adoc
> + * Server : RHEL machine
Instead of server we can call it "provisioner node" I feel

2016-11-17 15:07 UTC, shtripat commented on create_ceph_cluster_on_centos.adoc
> + * Server : RHEL machine
Better mention version details as well for OS

2016-11-17 15:07 UTC, shtripat commented on create_ceph_cluster_on_centos.adoc
> + * Register a node with the Red Hat Subscription Manager.
"Register the provisioner node with..."

2016-11-17 15:07 UTC, shtripat commented on create_ceph_cluster_on_centos.adoc
> + * (https://mojo.redhat.com/docs/DOC-97363)  For username
Remove the reference of this MOJO

2016-11-18 06:09 UTC, GowthamShanmugam commented on create_ceph_cluster_on_centos.adoc
> +using Rhel machine as sever.
ok i will change it shubhendhu

2016-11-18 06:11 UTC, GowthamShanmugam commented on create_ceph_cluster_on_centos.adoc
> + * Server : RHEL machine
i will change it

2016-11-18 06:11 UTC, GowthamShanmugam commented on create_ceph_cluster_on_centos.adoc
> + * Register a node with the Red Hat Subscription Manager.
ok

2016-11-18 06:11 UTC, GowthamShanmugam commented on create_ceph_cluster_on_centos.adoc
> + * (https://mojo.redhat.com/docs/DOC-97363)  For username
i will remove it

2016-11-23 07:09 UTC, GowthamShanmugam commented
@shtripat i have modified for upstream, please review it

2016-11-30 12:56 UTC, mbukatov commented on create_ceph_cluster_on_centos.adoc
> +== Install OS on Each Virtual Machines
Wouldn't be better to drop "Virtual" here? Installing ceph on virtual machines doesn't make with exception of some testing scenarios.

2016-11-30 12:56 UTC, mbukatov commented on create_ceph_cluster_on_centos.adoc
> +This document describes the mechanism to create ceph cluster on CentOS nodes
Could we have more context here? When would one need to follow this document when working with Tendrl?

2016-11-30 12:56 UTC, mbukatov commented on create_ceph_cluster_on_centos.adoc
> + * Provisioner Node : CentOs 7.0
I would suggest to do `s/CentOs 7.0/CentOS 7/` here.

2016-11-30 12:56 UTC, mbukatov commented on create_ceph_cluster_on_centos.adoc
> + * As root, start the firewalld service, enable it to run on boot, and ensure that it is running:
It would be nice to refer to ceph docs which describes firewall setup. Adding a link you used to write this up would be enough.

2016-11-30 13:03 UTC, r0h4n commented
This requires a github bug which describes clearly what is going on in this PR

2016-11-30 13:03 UTC, r0h4n requested changes
This requires a github bug which describes clearly what is going on in this PR

2016-12-01 05:25 UTC, GowthamShanmugam commented on create_ceph_cluster_on_centos.adoc
> +This document describes the mechanism to create ceph cluster on CentOS nodes
i will add brief description for this

2016-12-01 05:25 UTC, GowthamShanmugam commented on create_ceph_cluster_on_centos.adoc
> +== Install OS on Each Virtual Machines
i will correct it

2016-12-01 05:26 UTC, GowthamShanmugam commented on create_ceph_cluster_on_centos.adoc
> + * Provisioner Node : CentOs 7.0
As per your comment i will change that place

2016-12-01 05:26 UTC, GowthamShanmugam commented on create_ceph_cluster_on_centos.adoc
> + * As root, start the firewalld service, enable it to run on boot, and ensure that it is running:
i will add it

2016-12-01 05:27 UTC, GowthamShanmugam commented
i will raise github  for this

2016-12-01 11:26 UTC, GowthamShanmugam commented
@r0h4n , @brainfunked

2017-03-15 06:46 UTC, r0h4n approved these changes

2017-03-15 06:46 UTC, merged